pobintranetMVC/Controllers/05/001/KasaController.cs
using pobintranetMVC.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace pobintranetMVC.Controllers._05._001
{
    public class KasaController : Controller
    {
        public int ktoWprowadzil;

        public KasaController()
        {
        }

        public ActionResult ExportRozliczenieZaliczkiToIntranet()
        {
            List<ExcelRozliczenieZaliczki> item;
            intranetDataContext _intranetDataContext = new intranetDataContext();
            int num = (base.Session["kto"] != null ? Convert.ToInt32(base.Session["kto"]) : this.ktoWprowadzil);
            if (base.Session["Lista"] != null)
            {
                item = (List<ExcelRozliczenieZaliczki>)base.Session["Lista"];
            }
            else
            {
                item = null;
            }
            List<ExcelRozliczenieZaliczki> excelRozliczenieZaliczkis = item;
            if (excelRozliczenieZaliczkis == null)
            {
                ((dynamic)base.ViewBag).Error = "Nie udało się wgrac pliku";
                return base.View("UploadExcelRozliczenieZaliczki");
            }
            try
            {
                List<kasa> kasas = new List<kasa>();
                foreach (ExcelRozliczenieZaliczki excelRozliczenieZaliczki in excelRozliczenieZaliczkis)
                {
                    try
                    {
                        DateTime now = DateTime.Now;
                        kasa _kasa = new kasa()
                        {
                            IDPracownik = new int?(excelRozliczenieZaliczki.idpracownika),
                            TypOperacji = new char?('R'),
                            DataOperacji = new DateTime?(excelRozliczenieZaliczki.data),
                            OpisOperacji = excelRozliczenieZaliczki.tytul,
                            DataWpisu = new DateTime?(now),
                            CzasWpisu = new DateTime?(now),
                            Kwota = new decimal?(Convert.ToDecimal(excelRozliczenieZaliczki.kwota)),
                            Zatwierdzenie = false,
                            osobaWprowadzajaca = new int?(num),
                            dataWprowadzenia = new DateTime?(now),
                            zaliczkaZumowy = "T",
                            ids1 = new int?(1004),
                            ids2 = new int?(2084),
                            ida1 = new int?(3010),
                            ida2 = new int?(4069),
                            kontoKsiegowe = "238-0001-238-001",
                            export = new bool?(false),
                            nipPracownika = "",
                            nazwaK = "",
                            ulicaK = "",
                            kodK = "",
                            miastoK = "",
                            KwotaVat = new decimal?(new decimal()),
                            ProcentVat = new int?(100),
                            podlegaRozliczeniu = new bool?(false)
                        };
                        kasas.Add(_kasa);
                    }
                    catch (Exception)
                    {
                    }
                }
                _intranetDataContext.kasas.InsertAllOnSubmit<kasa>(kasas);
                _intranetDataContext.SubmitChanges();
            }
            catch (Exception)
            {
                ((dynamic)base.ViewBag).Error = "Nie udało się eksportować rekordów do intranetu.";
            }
            DateTime dateTime = DateTime.Now.AddDays(-1);
            string str = dateTime.ToString("dd-MM-yyyy");
            dateTime = DateTime.Now;
            string str1 = string.Format("http://int.poburski.local/aplikacje/05/001/raport_r04.asp?dataP={0}&dataK={1}&idprac=-1&konto=000-0000-000-000", str, dateTime.ToString("dd-MM-yyyy"));
            return this.Redirect(str1);
        }

        public ActionResult Index()
        {
            return base.View();
        }

        public ActionResult PreviewUploadRozliczenieZaliczki()
        {
            return base.View();
        }

        public ActionResult UploadExcelRozliczenieZaliczki()
        {
            this.WyczyscExcelCache();
            this.ktoWprowadzil = Convert.ToInt32(base.Request["kto"]);
            base.Session["Kto"] = this.ktoWprowadzil;
            return base.View();
        }

        [HttpPost]
        public ActionResult UploadRozliczenieZaliczki(HttpPostedFileBase excelFile)
        {
            base.Session["fileName"] = excelFile.FileName;
            if (excelFile == null || excelFile.ContentLength == 0)
            {
                ((dynamic)base.ViewBag).Error = "Proszę wybrać plik excel";
                return base.View("Index");
            }
            if (!excelFile.FileName.EndsWith("xls") && !excelFile.FileName.EndsWith("xlsx"))
            {
                ((dynamic)base.ViewBag).Error = "Wybrany plik nie jest plikiem excel(.xlsx , .xls)";
                return base.View("UploadExcelRozliczenieZaliczki");
            }
            string fileName = excelFile.FileName;
            try
            {
                HttpServerUtilityBase server = base.Server;
                DateTime now = DateTime.Now;
                fileName = server.MapPath(string.Concat("~/Excel/", now.ToString("ddMMyyyyThhmmss"), excelFile.FileName));
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception.Message);
            }
            if (System.IO.File.Exists(fileName))
            {
                System.IO.File.Delete(fileName);
            }
            excelFile.SaveAs(fileName);
            List<ExcelRozliczenieZaliczki> excelRozliczenieZaliczki = Help.GetExcelRozliczenieZaliczki(fileName, excelFile);
            ((dynamic)base.ViewBag).Lista = excelRozliczenieZaliczki;
            base.Session["Lista"] = excelRozliczenieZaliczki;
            return base.View("PreviewUploadRozliczenieZaliczki");
        }

        private void WyczyscExcelCache()
        {
            FileInfo[] files = (new DirectoryInfo(base.Server.MapPath("~/Excel/"))).GetFiles();
            for (int i = 0; i < (int)files.Length; i++)
            {
                files[i].Delete();
            }
        }
    }
}

pobintranetMVC/Views/Kasa/Index.cshtml
@{
    ViewBag.Title = "Kasa MVC";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kasa MVC</h2>

<p><a href="Kasa/UploadExcelRozliczenieZaliczki">Wgraj plik z rozliczeniami pracownika &raquo;</a></p>

pobintranetMVC/Views/Kasa/PreviewUploadRozliczenieZaliczki.cshtml
@using pobintranetMVC.Models
@{
    ViewBag.Title = "Podgląd wgranego pliku";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var index = 0;
    bool doWgrania = true;

    List<ExcelRozliczenieZaliczki> lista = ViewBag.Lista != null ? (List<ExcelRozliczenieZaliczki>)ViewBag.Lista : new List<ExcelRozliczenieZaliczki>();
    if (lista.Count == 0)
    {
        doWgrania = false;
    }
}

<script>
    document.getElementById("menuLink").href = "/aplikacje/05/001/start.asp";
    document.getElementById("naglowekStrony").innerHTML = ":: ROZLICZENIE ZALICZKI PRACOWNIKA"
    document.getElementById("numerAplikacjiStrony").innerHTML = "[A.05.001]"
    document.getElementById("tytulStrony").innerHTML = "Obsługa kasy gotówkowej (vMJ)"
    document.getElementById("tytulDzialu").innerHTML = "::: BIURO :::"
    $("#liniaPodDzialem").attr("background", "/tlo_fiolet.jpg")
</script>

<h2>Plik został importowany pomyślnie. Sprawdź czy dane się zgadzają.</h2>
<br />
@if (lista.Count > 0)
{
    <table border="1" style="width: 100%;">
        <tr>
            <td align="right">Lp.</td>
            <td>Pracownik</td>
            <td>Tytuł</td>
            <td>Data</td>
            <td align="right">Kwota</td>
        </tr>
        @foreach (ExcelRozliczenieZaliczki rozliczenie in lista)
        {
            index++;
            <tr>
                <td align="right">@index</td>
                @if (rozliczenie.idpracownika != 0)
                {
                    <td title="@rozliczenie.idpracownika">@rozliczenie.pracownik</td>
                }
                else
                {
                    doWgrania = false;
                    <td style="color: red;" title="@rozliczenie.idpracownika">@string.Format("{0} - BRAK TAKIEGO PRACOWNIKA, REKORD NIE BĘDZIE BRANY POD UWAGĘ, SPRAWDŹ CZY PRACOWNIK ISTNIEJE W iNTRANECIE", rozliczenie.pracownik)</td>
                }
                <td>@rozliczenie.tytul</td>
                <td nowrap>@rozliczenie.data.ToString("dd-MM-yyyy")</td>
                @if (rozliczenie.kwota != 0)
                {
                    <td align="right">@rozliczenie.kwota.ToString("C")</td>
                }
                else
                {
                    doWgrania = false;
                    <td align="right" style="color: red;">@rozliczenie.kwota.ToString("C")</td>
                }

            </tr>
        }
    </table>
}
<br />
@if (doWgrania)
{
    <p>@Html.ActionLink("WGRAJ DO INTRANETU", "ExportRozliczenieZaliczkiToIntranet", "Kasa", null, new { @class = "btn btn-primary" })</p>
}
else
{
    if (lista.Count == 0)
    {
        <p style="color: red;">BRAK REKORDÓW. CZY NA PEWNO TO TEN PLIK? @Html.ActionLink("WGRAJ OD NOWA", "UploadExcelRozliczenieZaliczki", "Kasa", new { lista = lista }, new { @class = "btn btn-primary" })</p>
    }
    else
    {
        <p style="color: red;">POPRAW BŁĘDY NA CZERWONO W TABELI I WGRAJ NA NOWO PLIK @Html.ActionLink("WGRAJ OD NOWA", "UploadExcelRozliczenieZaliczki", "Kasa", new { lista = lista }, new { @class = "btn btn-primary" })</p>
    }
}

pobintranetMVC/Views/Kasa/UploadExcelRozliczenieZaliczki.cshtml
@{
    ViewBag.Title = "Wgraj plik";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    document.getElementById("menuLink").href = "/aplikacje/05/001/start.asp";
    document.getElementById("naglowekStrony").innerHTML = ":: ROZLICZENIE ZALICZKI PRACOWNIKA"
    document.getElementById("numerAplikacjiStrony").innerHTML = "[A.05.001]"
    document.getElementById("tytulStrony").innerHTML = "Obsługa kasy gotówkowej (vMJ)"
    document.getElementById("tytulDzialu").innerHTML = "::: BIURO :::"
    $("#liniaPodDzialem").attr("background", "/tlo_fiolet.jpg")
</script>

<h2>Przygotuj i importuj plik(.xlsx , .xls)</h2>

@using (Html.BeginForm("UploadRozliczenieZaliczki", "Kasa", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <p class="red">@Html.Raw(ViewBag.Error)</p>
    <div style="position:relative;">
        <input type="file" accept=".xlsx, .xls" name="excelFile" size="40">
    </div>
    <br />
    <input type="submit" class="btn btn-primary" name="Submit" id="Submit" value="Importuj" />
}
<br />
<p>Plik do importu powinien mieć taki format:</p>
<table border="1">
    <tr>
        <td>&nbsp;</td>
        <td>A</td>
        <td>B</td>
        <td>C</td>
        <td>D</td>
    </tr>
    <tr>
        <td>1</td>
        <td>Kowalski Jan</td>
        <td>100</td>
        <td>Potrącenie zaliczki za Czerwiec 2019</td>
        <td>30-06-2019</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Nowak Andrzej</td>
        <td>300</td>
        <td>Potrącenie zaliczki za Czerwiec 2019</td>
        <td>30-06-2019</td>
    </tr>
</table>

<a href="/aplikacje/aplikacjeMVC/lokalnie2/csv/przyklad.xlsx">POBIERZ PRZYKŁAD</a> 