pobintranetMVC/Controllers/05/005/RozliczenieController.cs
using pobintranetMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace pobintranetMVC.Controllers._05._005
{
    public class RozliczenieController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Zaplac()
        {
            base.Session["listaDodanych"] = null;
            if (!string.IsNullOrEmpty(base.Request["zakupy"]))
            {
                intranetDataContext _intranetDataContext = new intranetDataContext();
                int num = int.Parse(base.Request["idkontrahenta"]);
                List<string> list = base.Request["zakupy"].ToString().Split(new char[] { ',' }).ToList<string>();
                List<rozrachunki_z> rozrachunkiZs = new List<rozrachunki_z>();
                foreach (string str in list)
                {
                    try
                    {
                        rozrachunki_z rozrachunkiZ = (
                            from z in _intranetDataContext.rozrachunki_zs
                            where z.idzakupu == Convert.ToInt32(str)
                            select z).First<rozrachunki_z>();
                        rozrachunkiZs.Add(rozrachunkiZ);
                    }
                    catch (Exception)
                    {

                    }
                }
                ((dynamic)base.ViewBag).Id = num;
                ((dynamic)base.ViewBag).Lista = rozrachunkiZs;
            }
            else
            {
                HttpResponseBase response = base.Response;
                DateTime now = DateTime.Now;
                response.Redirect(string.Format("/aplikacje/05/005/lista_sald.asp?ujemne=P&dodatnie=P&rok={0}", now.Year));
            }
            return base.View();
        }

        public ActionResult ZaplacSprzedaz()
        {
            base.Session["listaDodanychSprzedaz"] = null;
            if (!string.IsNullOrEmpty(base.Request["zakupy"]))
            {
                intranetDataContext _intranetDataContext = new intranetDataContext();
                int num = int.Parse(base.Request["idkontrahenta"]);
                List<string> list = base.Request["zakupy"].ToString().Split(new char[] { ',' }).ToList<string>();
                List<rozrachunki_> rozrachunkiSs = new List<rozrachunki_>();
                foreach (string str in list)
                {
                    try
                    {
                        rozrachunki_ rozrachunkiS = (
                            from s in _intranetDataContext.rozrachunki_s
                            where s.idsprzedazy == Convert.ToInt32(str)
                            select s).First<rozrachunki_>();
                        rozrachunkiSs.Add(rozrachunkiS);
                    }
                    catch (Exception)
                    {

                    }
                }
                ((dynamic)base.ViewBag).Id = num;
                ((dynamic)base.ViewBag).Lista = rozrachunkiSs;
            }
            else
            {
                HttpResponseBase response = base.Response;
                DateTime now = DateTime.Now;
                response.Redirect(string.Format("/aplikacje/05/005/lista_sald.asp?ujemne=P&dodatnie=P&rok={0}", now.Year));
            }
            return base.View();
        }

        [HttpPost]
        public ActionResult ZaplacFaktury(FormCollection request)
        {
            int num = Convert.ToInt32(request["idkontrahenta"]);
            int num1 = Convert.ToInt32(request["ilosc"]);
            List<RozliczenieController.ZakupRozliczenie> zakupRozliczenies = new List<RozliczenieController.ZakupRozliczenie>();
            for (int i = 0; i < num1; i++)
            {
                RozliczenieController.ZakupRozliczenie zakupRozliczenie = new RozliczenieController.ZakupRozliczenie()
                {
                    data = Help.ZmianaDatyNaSQL(request[string.Concat("zakup[", i, "].data_platnosci")]),
                    idzakupu = Convert.ToInt32(request[string.Concat("zakup[", i, "].idzakupu")])
                };
                try
                {
                    zakupRozliczenie.kwota = Convert.ToDouble(request[string.Concat("zakup[", i, "].zaplacono")].Replace(".", ","));
                }
                catch (Exception)
                {
                    zakupRozliczenie.kwota = Convert.ToDouble(request[string.Concat("zakup[", i, "].zaplacono")]);
                }
                try
                {
                    zakupRozliczenie.vat = Convert.ToDouble(request[string.Concat("zakup[", i, "].vat")].Replace(".", ","));
                }
                catch (Exception)
                {
                    zakupRozliczenie.vat = Convert.ToDouble(request[string.Concat("zakup[", i, "].vat")]);
                }
                zakupRozliczenies.Add(zakupRozliczenie);
            }
            List<int> nums = new List<int>();
            if (base.Session["listaDodanych"] != null)
            {
                nums = (List<int>)base.Session["listaDodanych"];
            }
            intranetDataContext _intranetDataContext = new intranetDataContext();
            List<rozrachunek> rozrachuneks = new List<rozrachunek>();
            foreach (RozliczenieController.ZakupRozliczenie zakupRozliczenie1 in zakupRozliczenies.Distinct<RozliczenieController.ZakupRozliczenie>())
            {
                if ((
                    from ld in nums
                    where ld == zakupRozliczenie1.idzakupu
                    select ld).Any<int>())
                {
                    continue;
                }
                if ((
                    from r in _intranetDataContext.rozrachuneks
                    where (r.data_operacji == (DateTime?)DateTime.Parse(zakupRozliczenie1.data)) && r.kwota_rozchod_pln == (double?)zakupRozliczenie1.kwota && r.idzakupu == (int?)zakupRozliczenie1.idzakupu
                    select r).Any<rozrachunek>() || zakupRozliczenie1.kwota <= 0)
                {
                    continue;
                }
                rozrachunek _rozrachunek = new rozrachunek()
                {
                    idkontrahenta = num == 0 ? Help.GetZakup(zakupRozliczenie1.idzakupu).idkontrahenta : num,
                    data_operacji = new DateTime?(DateTime.Parse(zakupRozliczenie1.data)),
                    idzakupu = new int?(zakupRozliczenie1.idzakupu),
                    kwota_rozchod_pln = new double?(zakupRozliczenie1.kwota),
                    czas_wpisu = new DateTime?(DateTime.Now),
                    kwota_przychod_pln = new double?(0),
                    kwotaPrzychodFBZ = new double?(0),
                    kwotaPrzychodZCZ = new double?(0),
                    kwotaPrzychodZGW = new double?(0),
                    kwotaRozchodFBZ = new double?(zakupRozliczenie1.kwota),
                    kwotaRozchodZCZ = new double?(0),
                    kwotaRozchodZGW = new double?(0),
                    kwotaRozchodVAT = zakupRozliczenie1.vat,
                    opis = "Zapłacono wiele " + DateTime.Now.ToString("dd-MM-yyyy hh:mm")
                };
                rozrachuneks.Add(_rozrachunek);
                nums.Add(zakupRozliczenie1.idzakupu);
            }
            base.Session["listaDodanych"] = nums;
            _intranetDataContext.rozrachuneks.InsertAllOnSubmit<rozrachunek>(rozrachuneks);
            _intranetDataContext.SubmitChanges();
            _intranetDataContext.popraw_kontrahenta_rozrachunki();
            return this.Redirect(string.Format("/aplikacje/05/005/lista_sald.asp?ujemne=P&dodatnie=P", num));
        }

        [HttpPost]
        public ActionResult ZaplacFakturySprzedaz(FormCollection request)
        {
            int num = Convert.ToInt32(request["idkontrahenta"]);
            int num1 = Convert.ToInt32(request["ilosc"]);
            List<RozliczenieController.SprzedazRozliczenie> zakupRozliczenies = new List<RozliczenieController.SprzedazRozliczenie>();
            for (int i = 0; i < num1; i++)
            {
                RozliczenieController.SprzedazRozliczenie zakupRozliczenie = new RozliczenieController.SprzedazRozliczenie()
                {
                    data = Help.ZmianaDatyNaSQL(request[string.Concat("zakup[", i, "].data_platnosci")]),
                    idsprzedazy = Convert.ToInt32(request[string.Concat("zakup[", i, "].idsprzedazy")])
                };
                try
                {
                    zakupRozliczenie.kwota = Convert.ToDouble(request[string.Concat("zakup[", i, "].zaplacono")].Replace(".", ","));
                }
                catch (Exception)
                {
                    zakupRozliczenie.kwota = Convert.ToDouble(request[string.Concat("zakup[", i, "].zaplacono")]);
                }
                try
                {
                    zakupRozliczenie.vat = Convert.ToDouble(request[string.Concat("zakup[", i, "].vat")].Replace(".", ","));
                }
                catch (Exception)
                {
                    zakupRozliczenie.vat = Convert.ToDouble(request[string.Concat("zakup[", i, "].vat")]);
                }
                zakupRozliczenies.Add(zakupRozliczenie);
            }
            List<int> nums = new List<int>();
            if (base.Session["listaDodanych"] != null)
            {
                nums = (List<int>)base.Session["listaDodanych"];
            }
            intranetDataContext _intranetDataContext = new intranetDataContext();
            List<rozrachunek> rozrachuneks = new List<rozrachunek>();
            foreach (RozliczenieController.SprzedazRozliczenie zakupRozliczenie1 in zakupRozliczenies.Distinct<RozliczenieController.SprzedazRozliczenie>())
            {
                if ((
                    from ld in nums
                    where ld == zakupRozliczenie1.idsprzedazy
                    select ld).Any<int>())
                {

pobintranetMVC/Views/Rozliczenie/Zaplac.cshtml
@using pobintranetMVC.Models
@{
    ViewBag.Title = "iNTRANET - Poburski Dachtechnik Sp. z o.o.";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<rozrachunki_z> lista = (List<rozrachunki_z>)ViewBag.Lista;
    var kontrahent = ViewBag.Id;
    int rekord = -1;
    double sumaKwota = 0;
    double sumaZaplacono = 0;

    int? idwysylki = Convert.ToInt32(Request["idwysylki"]);
}
@* Tytuły i linki dla strony *@
<script>
    document.getElementById("menuLink").href = "/aplikacje/05/005/start.asp";
    document.getElementById("naglowekStrony").innerHTML = ":: ZAPŁAĆ SALDO KONTRAHENTA"
</script>

@using (Html.BeginForm("ZaplacFaktury", "Rozliczenie", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
{
    <input type="hidden" name="idkontrahenta" value="@kontrahent" />
    <input hidden name="ilosc" value="@lista.Count" />

    <table style="width: 100%;" cellpadding="10" border="1">
        <tr>
            <td style="font-weight: bold;" align="right">Lp.</td>
            <td style="font-weight: bold;">Nazwa dokumentu</td>
            <td style="font-weight: bold;">Kontrahent</td>
            <td style="font-weight: bold;" align="right">Kwota faktury</td>
            <td style="font-weight: bold;" align="right">Zapłacono już</td>
            <td style="font-weight: bold;">Data płatności</td>
            <td style="font-weight: bold;" align="center">Zapłać</td>
            <td style="font-weight: bold;" align="center">VAT</td>
        </tr>
        @foreach (var rozrachunek in lista.OrderBy(l => Help.GetNazwaKontrahenta(l.idkontahenta, false)))
        {
            rekord++;
    <tr>
        <td align="right">@string.Format("{0}.", rekord + 1)</td>
        <td><input type="hidden" name="zakup[@rekord].idzakupu" value="@rozrachunek.idzakupu" /><p><a href="/aplikacje/05/004/koszt.asp?id_koszt=@rozrachunek.idzakupu" target="_blank">@rozrachunek.dok</a></p></td>
        <td title="@rozrachunek.idkontahenta">@Help.GetNazwaKontrahenta(rozrachunek.idkontahenta, false)</td>
        <td align="right"><p>@Convert.ToDouble(rozrachunek.kwota).ToString("C").Replace(",", ".")</p></td>
        <td align="right"><p>@Convert.ToDouble(rozrachunek.zaplacono).ToString("C").Replace(",", ".")</p></td>
        @*<td width="150"><input type="text" value="06-08-2020" name="zakup[@rekord].data_platnosci" class="form-control" /></td>*@
        <td width="150"><input type="text" value="@DateTime.UtcNow.ToString("dd-MM-yyyy")" name="zakup[@rekord].data_platnosci" class="form-control" /></td>
        <td width="180" align="center">
            <input type="number" step="0.01" min="0.00" max="@Convert.ToDouble(rozrachunek.kwota-rozrachunek.zaplacono).ToString().Replace(",", ".")" value="@Convert.ToDouble(Help.GetKwotaRozrachunkuZWysylki(rozrachunek.kwota, idwysylki, rozrachunek.idzakupu)-rozrachunek.zaplacono).ToString().Replace(",", ".")" class="form-control doSumy" name="zakup[@rekord].zaplacono" id="@string.Format("zakup{0}", rekord)" onkeydown="policzSume()" onclick="$(this).focus();" />
        </td>
        <td width="180" align="center">
            <input type="number" step="0.01" min="0.00" max="@Convert.ToDouble(rozrachunek.vat-rozrachunek.vat_zaplacono).ToString().Replace(",", ".")" value="@Convert.ToDouble(Help.GetVatRozrachunkuZWysylki(rozrachunek.vat, idwysylki, rozrachunek.idzakupu)-rozrachunek.vat_zaplacono).ToString().Replace(",", ".")" class="form-control" name="zakup[@rekord].vat" id="@string.Format("vat{0}", rekord)" onclick="$(this).focus();" />
        </td>
    </tr>
            sumaKwota += Convert.ToDouble(rozrachunek.kwota);
            sumaZaplacono += Convert.ToDouble(rozrachunek.zaplacono);
        }
    <tr>
        <td colspan="3" align="right"><b>SUMA</b></td>
        <td align="right" nowrap><b>@sumaKwota.ToString("C").Replace(",", ".")</b></td>
        <td align="right" nowrap><b>@sumaZaplacono.ToString("C").Replace(",", ".")</b></td>
        <td width="150"></td>
        <td width="180" align="right"><span id="suma" style="font-weight: bold;">@sumaKwota.ToString("C"))</span></td>
        <td width="150"></td>
    </tr>
    </table>
    <br />
    <button class="btn btn-primary" id="submitButton" data-confirm="Czy na pewno chcesz zapłacić te faktury?">Zapłać</button>
}

<script>
    policzSume();
    $(function () {
        $(document).keydown(function (e) {
            return (e.which || e.keyCode) != 116;
        });
    });

    $(document).ready(function () {
        $('#submitButton').click(function (e) {
            if (!confirm($(this).attr("data-confirm"))) {
                e.preventDefault();
            }
            else {
                this.disabled = true;
                $("#form").submit();
            }
        });
    });

    function policzSume() {
        suma = 0;
        $(".doSumy").each(function (index) {
            suma += parseFloat($(this).val());
        });
        $("#suma").text(suma + " zł");
    }

    //jQuery("input.doSumy").on("keydown", function (e) {
    //    if (e.keyCode === 190) { alert("Wstaw przecinek zamiast kropki!"); e.preventDefault(); }
    //});
</script>

pobintranetMVC/Views/Rozliczenie/ZaplacSprzedaz.cshtml
@using pobintranetMVC.Models
@{
    ViewBag.Title = "iNTRANET - Poburski Dachtechnik Sp. z o.o.";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<rozrachunki_> lista = (List<rozrachunki_>)ViewBag.Lista;
    var kontrahent = ViewBag.Id;
    int rekord = -1;
    double sumaKwota = 0;
    double sumaZaplacono = 0;

    int? idwysylki = Convert.ToInt32(Request["idwysylki"]);
}
@* Tytuły i linki dla strony *@
<script>
    document.getElementById("menuLink").href = "/aplikacje/05/005/start.asp";
    document.getElementById("naglowekStrony").innerHTML = ":: ZAPŁAĆ SALDO KONTRAHENTA"
</script>

@using (Html.BeginForm("ZaplacFakturySprzedaz", "Rozliczenie", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
{
    <input type="hidden" name="idkontrahenta" value="@kontrahent" />
    <input hidden name="ilosc" value="@lista.Count" />

    <table style="width: 100%;" cellpadding="10" border="1">
        <tr>
            <td style="font-weight: bold;" align="right">Lp.</td>
            <td style="font-weight: bold;">Nazwa dokumentu</td>
            <td style="font-weight: bold;">Kontrahent</td>
            <td style="font-weight: bold;" align="right">Kwota faktury</td>
            <td style="font-weight: bold;" align="right">Zapłacono już</td>
            <td style="font-weight: bold;">Data płatności</td>
            <td style="font-weight: bold;" align="center">Zapłać</td>
            <td style="font-weight: bold;" align="center">VAT</td>
        </tr>
        @foreach (var rozrachunek in lista.OrderBy(l => Help.GetNazwaKontrahenta(l.idkontahenta, false)))
        {
            rekord++;
            <tr>
                <td align="right">@string.Format("{0}.", rekord + 1)</td>
                <td><input type="hidden" name="zakup[@rekord].idsprzedazy" value="@rozrachunek.idsprzedazy" /><p><a href="/aplikacje/05/004/koszt.asp?id_koszt=@rozrachunek.idsprzedazy" target="_blank">@rozrachunek.dok</a></p></td>
                <td title="@rozrachunek.idkontahenta">@Help.GetNazwaKontrahenta(rozrachunek.idkontahenta, false)</td>
                <td align="right"><p>@Convert.ToDouble(rozrachunek.kwota).ToString("C").Replace(",", ".")</p></td>
                <td align="right"><p>@Convert.ToDouble(rozrachunek.zaplacono).ToString("C").Replace(",", ".")</p></td>
                @*<td width="150"><input type="text" value="06-08-2020" name="zakup[@rekord].data_platnosci" class="form-control" /></td>*@
                <td width="150"><input type="text" value="@DateTime.UtcNow.ToString("dd-MM-yyyy")" name="zakup[@rekord].data_platnosci" class="form-control" /></td>
                <td width="180" align="center">
                    <input type="number" step="0.01" min="0.00" max="@Convert.ToDouble(rozrachunek.kwota-rozrachunek.zaplacono).ToString().Replace(",", ".")" value="@Convert.ToDouble(Help.GetKwotaRozrachunkuZWysylki(rozrachunek.kwota, idwysylki, rozrachunek.idsprzedazy)-rozrachunek.zaplacono).ToString().Replace(",", ".")" class="form-control doSumy" name="zakup[@rekord].zaplacono" id="@string.Format("zakup{0}", rekord)" onkeydown="policzSume()" onclick="$(this).focus();" />
                </td>
                <td width="180" align="center">
                    <input type="number" step="0.01" min="0.00" max="@Convert.ToDouble(rozrachunek.vat-rozrachunek.vat_zaplacono).ToString().Replace(",", ".")" value="@Convert.ToDouble(Help.GetVatRozrachunkuZWysylki(rozrachunek.vat, idwysylki, rozrachunek.idsprzedazy)-rozrachunek.vat_zaplacono).ToString().Replace(",", ".")" class="form-control" name="zakup[@rekord].vat" id="@string.Format("vat{0}", rekord)" onclick="$(this).focus();" />
                </td>
            </tr>
            sumaKwota += Convert.ToDouble(rozrachunek.kwota);
            sumaZaplacono += Convert.ToDouble(rozrachunek.zaplacono);
        }
        <tr>
            <td colspan="3" align="right"><b>SUMA</b></td>
            <td align="right" nowrap><b>@sumaKwota.ToString("C").Replace(",", ".")</b></td>
            <td align="right" nowrap><b>@sumaZaplacono.ToString("C").Replace(",", ".")</b></td>
            <td width="150"></td>
            <td width="180" align="right"><span id="suma" style="font-weight: bold;">@sumaKwota.ToString("C"))</span></td>
            <td width="150"></td>
        </tr>
    </table>
    <br />
    <button class="btn btn-primary" id="submitButton" data-confirm="Czy na pewno chcesz zapłacić te faktury?">Zapłać</button>
}

<script>
    policzSume();
    $(function () {
        $(document).keydown(function (e) {
            return (e.which || e.keyCode) != 116;
        });
    });

    $(document).ready(function () {
        $('#submitButton').click(function (e) {
            if (!confirm($(this).attr("data-confirm"))) {
                e.preventDefault();
            }
            else {
                this.disabled = true;
                $("#form").submit();
            }
        });
    });

    function policzSume() {
        suma = 0;
        $(".doSumy").each(function (index) {
            suma += parseFloat($(this).val());
        });
        $("#suma").text(suma + " zł");
    }

    //jQuery("input.doSumy").on("keydown", function (e) {
    //    if (e.keyCode === 190) { alert("Wstaw przecinek zamiast kropki!"); e.preventDefault(); }
    //});
</script>