pobintranetMVC/Controllers/02/003/ZamowienieController.cs
using pobintranetMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace pobintranetMVC.Controllers._02._003
{
    public class ZamowienieController : Controller
    {
        // GET: Zamowienie
        public ActionResult Index(int? idz)
        {
            if (idz == null)
            {
                Response.Redirect("/zamowienia/ZamowieniaLista.aspx");
            }

            intranetDataContext dc = new intranetDataContext();
            List<zamowieniaPozycje> pozycje = dc.zamowieniaPozycjes.Where(p => p.IdZamowienia == idz).ToList();
            zamowieniaDokument dokument = dc.zamowieniaDokuments.Where(d => d.IdZamowienia == idz).First();

            ViewBag.Pozycje = pozycje;
            ViewBag.Dokument = dokument;

            return View();
        }

        public ActionResult LadujUlubione()
        {
            intranetDataContext dc = new intranetDataContext();
            var lista = dc.zamowieniaTopKontrahencis.OrderBy(ztk => ztk.liczba).Take(5).ToList();
            var lista2 = dc.kontrahents.Where(k => k.nazwa.ToLower().Contains("enteli") || k.nazwa.ToLower().Contains("alfa elektro") || k.nazwa.ToLower().Contains("tim spółka akcyjna") || k.nazwa.ToLower().Contains("el 12") || k.nazwa.ToLower().Contains("onninen")).ToList();

            ViewBag.Lista = lista;
            ViewBag.Lista2 = lista2;
            return View();
        }

        public ActionResult Faktury(int id)
        {
            intranetDataContext dc = new intranetDataContext();
            List<zakup_zamowienia> zz = dc.zakup_zamowienias.Where(z => z.id_zakupu == id).OrderBy(z => z.data_wprowadzenia).ToList();

            ViewBag.Lista = zz;

            return View();
        }

        public void UsunFakture(int id, int idz)
        {
            intranetDataContext dc = new intranetDataContext();
            zakup_zamowienia zz = dc.zakup_zamowienias.Where(z => z.id == id).First();
            dc.zakup_zamowienias.DeleteOnSubmit(zz);
            dc.SubmitChanges();

            Response.Redirect("/aplikacje/05/004/koszt.asp?id_koszt=" + idz);
        }

        [HttpPost]
        public void DodajZakupDoZamowienia(int idz, int id_zam, string kwota, int zu, int p)
        {
            intranetDataContext dc = new intranetDataContext();
            zakup_zamowienia zz = new zakup_zamowienia();
            zz.id_zamowienia = id_zam;
            zz.id_zakupu = idz;
            try
            {
                zz.kwota = float.Parse(kwota);
            }
            catch (Exception)
            {
                zz.kwota = float.Parse(kwota.Replace(".", ","));
            }
            zz.kto_wprowadzil = zu;
            zz.data_wprowadzenia = DateTime.Now;
            zz.pozycja = p.ToString();
            dc.zakup_zamowienias.InsertOnSubmit(zz);
            dc.SubmitChanges();

            Response.Redirect("/aplikacje/05/004/koszt.asp?id_koszt=" + idz);
        }

        public void ZatwierdzCeny(int idz)
        {
            intranetDataContext dc = new intranetDataContext();
            var pozycje = dc.zamowieniaPozycjes.Where(zp => zp.IdZamowienia == idz).ToList();
            foreach (var p in pozycje)
            {
                var mat = dc.magazyn_materialies.Where(mm => mm.idmaterialu == p.IdMaterialu).First();
                decimal nowa_cena = Convert.ToDecimal(Math.Round(Convert.ToDouble(p.MaterialCenaJednostkowa), 2, MidpointRounding.AwayFromZero));
                decimal stara_cena = Convert.ToDecimal(Math.Round(Convert.ToDouble(mat.cena_katolofowa), 2, MidpointRounding.AwayFromZero));
                Help.WpiszCenyMaterialuDoArchiwum(p.IdMaterialu, stara_cena, nowa_cena);
                try
                {
                    mat.cena_katolofowa = nowa_cena;
                    dc.SubmitChanges();
                }
                catch (Exception)
                {
                    continue;
                }
            }
        }

        public ActionResult SelectZamowienia(int? producent)
        {
            intranetDataContext dc = new intranetDataContext();
            var lista = dc.zamowieniaDokuments.OrderByDescending(zd => zd.DataWpisu).ToList();
            if (producent != null)
            {
                lista = lista.Where(l => l.IdKontrahenta == producent).ToList();
            }
            List<zamowieniaDokument> vblista = new List<zamowieniaDokument>();
            foreach (var z in lista)
            {
                try
                {
                    var suma1 = Math.Round(Convert.ToDecimal(dc.zamowieniaPozycjes.Where(zp => zp.IdZamowienia == z.IdZamowienia).Sum(zp => Math.Round(Convert.ToDecimal(zp.WartoscPozycji), 2, MidpointRounding.AwayFromZero))), 2, MidpointRounding.AwayFromZero);
                    var suma2 = Math.Round(Convert.ToDecimal(dc.zakup_zamowienias.Where(zp => zp.id_zamowienia == z.IdZamowienia).Sum(zp => zp.kwota)), 2, MidpointRounding.AwayFromZero);

                    if (suma1 - suma2 != 0)
                    {
                        vblista.Add(z);
                    }
                }
                catch (Exception)
                {

                }

            }
            ViewBag.Lista = vblista;
            return View();
        }

        public ActionResult GetFakturyDoZamowienia(int id)
        {
            intranetDataContext dc = new intranetDataContext();
            List<zakup_zamowienia> zz = dc.zakup_zamowienias.Where(z => z.id_zamowienia == id).OrderBy(z => z.data_wprowadzenia).ToList();

            ViewBag.Lista = zz;

            return View();
        }

        public string SelectCena(int id)
        {
            try
            {
                intranetDataContext dc = new intranetDataContext();
                return Help.GetSumaZamowieniaZPozycji(id);
            }
            catch (Exception)
            {
                return "0.00";
            }
        }

        public string SelectCena2(int id, decimal max)
        {
            try
            {
                intranetDataContext dc = new intranetDataContext();
                if (Convert.ToDecimal(Help.GetSumaZamowieniaZPozycji2(id)) > max)
                {
                    return max.ToString();
                }
                return Help.GetSumaZamowieniaZPozycji2(id);
            }
            catch (Exception)
            {
                return "0.00";
            }
        }

        public ActionResult ZamowienieDoPozycji(int id, float max, int pozycja)
        {
            return View();
        }

        public ActionResult DuplikujZamowienie(int id)
        {
            intranetDataContext dc = new intranetDataContext();
            var zd = dc.zamowieniaDokuments.Where(z => z.IdZamowienia == id).First();
            var pozycjeDuplikowane = dc.zamowieniaPozycjes.Where(zp => zp.IdZamowienia == id).ToList();

            var nz = new zamowieniaDokument();
            nz.DataWpisu = DateTime.Now;
            nz.KtoWpisal = zd.KtoWpisal;
            nz.Modyfikowano = false;
            nz.DataModyfikacji = DateTime.Now;
            nz.Usunieto = zd.Usunieto;
            nz.KtoUsunal = zd.KtoUsunal;
            nz.Status = zd.Status;
            nz.NrProjektu = zd.NrProjektu;
            nz.IdProjektu = zd.IdProjektu;
            nz.DataZamowienia = zd.DataZamowienia;
            nz.NrZamowienia = dc.nadajNrZamowienia(nz.NrProjektu, nz.DataZamowienia);
            nz.ProjektNazwa = zd.ProjektNazwa;
            nz.ProjektAdres = zd.ProjektAdres;
            nz.KontrahentOsoba = zd.KontrahentOsoba;
            nz.KontrahentNazwa = zd.KontrahentNazwa;
            nz.KontrahentUlica = zd.KontrahentUlica;
            nz.IdKontrahenta = zd.IdKontrahenta;
            nz.KontrahentKod = zd.KontrahentKod;
            nz.KontrahentMiejscowosc = zd.KontrahentMiejscowosc;
            nz.KontrahentEmail = zd.KontrahentEmail;
            nz.KontrahentTelefon = zd.KontrahentTelefon;
            nz.KontrahentFax = zd.KontrahentFax;
            nz.FakturaNazwa = zd.FakturaNazwa;
            nz.FakturaOsoba = zd.FakturaOsoba;
            nz.FakturaUlica = zd.FakturaUlica;
            nz.FakturaKod = zd.FakturaKod;
            nz.FakturaMiejscowosc = zd.FakturaMiejscowosc;
            nz.KontaktOsoba = zd.KontaktOsoba;
            nz.KontaktEmail = zd.KontaktEmail;
            nz.KontaktFax = zd.KontaktFax;
            nz.KontaktTelefon = zd.KontaktTelefon;
            nz.WaznoscOferty = zd.WaznoscOferty;
            nz.SumaNetto = zd.SumaNetto;
            nz.Gwarancja = zd.Gwarancja;
            nz.GwarancjaOpis = zd.GwarancjaOpis;
            nz.TerminDostawy = zd.TerminDostawy;
            nz.TerminDostawyOpis = zd.TerminDostawyOpis;
            nz.TerminDostawyGodzina = zd.TerminDostawyGodzina;
            nz.Platnosc = zd.Platnosc;
            nz.PlatnoscOpis = zd.PlatnoscOpis;
            nz.ZamowienieOpis = zd.ZamowienieOpis;
            nz.OfertaZdnia = zd.OfertaZdnia;
            nz.ZnakWlasny = zd.ZnakWlasny;
            nz.ZnakObcy = zd.ZnakObcy;
            nz.PowierzchniaDachu = zd.PowierzchniaDachu;
            nz.Zatwierdzono = false;
            nz.KtoZatwierdzil = "";
            nz.DataZatwierdzenia = null;
            nz.Konstrukcja = zd.Konstrukcja;
            nz.NrZamowieniaKontrahenta = zd.NrZamowieniaKontrahenta;
            nz.OsobaOdpID = zd.OsobaOdpID;
            nz.OsobaOdpImie = zd.OsobaOdpImie;
            nz.OsobaOdpNazwisko = zd.OsobaOdpNazwisko;
            nz.OsobaOdpTelefon = zd.OsobaOdpTelefon;
            nz.OsobaOdpFax = zd.OsobaOdpFax;
            nz.OsobaOdpEmail = zd.OsobaOdpEmail;

            dc.zamowieniaDokuments.InsertOnSubmit(nz);
            dc.SubmitChanges();

            List<zamowieniaPozycje> nowePozycje = new List<zamowieniaPozycje>();
            foreach (var sp in pozycjeDuplikowane)
            {
                var np = new zamowieniaPozycje();

pobintranetMVC/Views/Zamowienie/Faktury.cshtml
@using pobintranetMVC.Models
@{
    Layout = null;
    List<zakup_zamowienia> lista = (List<zakup_zamowienia>)ViewBag.Lista;
}
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

<script src="~/Scripts/selectize.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css">

@if (lista.Count == 0)
{
    <p style="color: red;">BRAK ZAMÓWIEŃ</p>
}
else
{
    int lp = 0;
    <table style="width: 100%" ; border="1">
        <tr>
            <td><b>Lp.</b></td>
            <td><b>Data</b></td>
            <td><b>Zamówienie</b></td>
            <td align="right"><b>Pozycja</b></td>
            <td align="center"><b>Kto wprowadził</b></td>
            <td align="center"><b>Akcje</b></td>
        </tr>
        @foreach (var z in lista)
        {
            lp += 1;
    <tr>
        <td>@lp</td>
        <td>@z.data_wprowadzenia.ToString("dd-MM-yyyy")</td>
        <td>@Help.GetNumerZamowienia(z.id_zamowienia)</td>
        <td align="right">@z.pozycja</td>
        @*<td align="right">@Math.Round(Convert.ToDouble(z.kwota), 2 , MidpointRounding.AwayFromZero)</td>*@
        <td align="center">@Help.GetImieNazwiskoPracownika(z.kto_wprowadzil)</td>
        <td align="center"><a href="/aplikacjeMVC/Zamowienie/UsunFakture?id=@z.id&idz=@z.id_zakupu">Usuń</a></td>
    </tr>
        }
    </table>
}

pobintranetMVC/Views/Zamowienie/GetFakturyDoZamowienia.cshtml
@using pobintranetMVC.Models
@{
    Layout = null;
    List<zakup_zamowienia> lista = (List<zakup_zamowienia>)ViewBag.Lista;
}

@if (lista.Count == 0)
{

    <p style="color: red;">BRAK FAKTUR</p>
}
else
{
    int lp = 0;
    <table style="width: 100%" ; border="1">
        <tr>
            <td><b>Lp.</b></td>
            <td><b>Data</b></td>
            <td><b>Zamówienie</b></td>
            <td align="right"><b>Kwota</b></td>
            <td align="center"><b>Kto wprowadził</b></td>
        </tr>
        @foreach (var z in lista)
        {
            lp += 1;
            <tr>
                <td>@lp</td>
                <td>@z.data_wprowadzenia.ToString("dd-MM-yyyy")</td>
                <td>@Help.GetNumerZamowienia(z.id_zamowienia)</td>
                <td align="right">@Math.Round(Convert.ToDouble(z.kwota), 2, MidpointRounding.AwayFromZero)</td>
                <td align="center">@Help.GetImieNazwiskoPracownika(z.kto_wprowadzil)</td>
            </tr>
        }
    </table>
}

pobintranetMVC/Views/Zamowienie/GetRealizacjeRaport.cshtml
@using pobintranetMVC.Models
@{
    Layout = null;
    List<zamowieniaPozycjaOpi> lista = (List<zamowieniaPozycjaOpi>)ViewBag.Lista;
    var index = 0;
}
@if (lista.Count > 0)
{
    <tr style="background-color: #a8a497; display: none;" class="realizacje">
        <td colspan="2" rowspan="@string.Format("{0}", lista.Count+1)" style="font-weight: bold;" align="right" valign="top">Realizacje</td>
        <td><div align="right">Lp.</div></td>
        <td>Data realizacji</td>
        <td><div align="right">Ilość</div></td>
        <td colspan="3">Budowa</td>
    </tr>
    foreach (var l in lista)
    {
        index += 1;
        var budowa = Help.GetBudowa(l.id_projektu);
        <tr style="background-color: #a8a497; display: none;" class="realizacje">
            @*<td colspan="2">&nbsp;</td>*@
            <td><div align="right">@index</div></td>
            <td>@l.data.ToShortDateString()</td>
            <td><div align="right">@l.ilosc</div></td>
            <td colspan="3">@string.Format("[{0}] {1}", budowa.numer, budowa.nazwa)</td>
        </tr>
    }
}

pobintranetMVC/Views/Zamowienie/LadujUlubione.cshtml
@using pobintranetMVC
@using pobintranetMVC.Models
@{
    Layout = null;
    var lista = (List<zamowieniaTopKontrahenci>)ViewBag.Lista;
    var lista2 = (List<kontrahent>)ViewBag.Lista2;

    var lista3 = lista;
    foreach (var l in lista2)
    {
        if (!lista.Where(l1 => l1.IdKontrahenta == l.idkontahenta).Any())
        {
            var z = new zamowieniaTopKontrahenci();
            z.IdKontrahenta = l.idkontahenta;
            z.liczba = 0;
            lista3.Add(z);
        }
    }
}

<option selected="selected" value="">WYBIERZ ULUBIONEGO</option>



@foreach (var l in lista3)
{
    <option value="@Help.GetNipKontrahenta(l.IdKontrahenta)">@Help.GetNazwaKontrahenta(l.IdKontrahenta, true)</option>
}

pobintranetMVC/Views/Zamowienie/SelectZamowienia.cshtml
@using pobintranetMVC.Models
@{
    Layout = null;

    List<zamowieniaDokument> zamowienia = (List<zamowieniaDokument>)ViewBag.Lista;
}

<select id="selectzamowienie" name="id_zam" onload="$(this).val('')" onclick="" runat="server" class="wpisy_dp_male" style="width: 100%" required>
    <option value="" disabled selected></option>
    @foreach (zamowieniaDokument z in zamowienia)
    {
        <option value="@z.IdZamowienia" data-cena="@z.SumaNetto">@string.Format("{0} | {1} | {2} | {3}", z.NrZamowienia, z.ZnakWlasny , z.DataZamowienia.Value.ToString("dd-MM-yyyy"), Help.GetSumaZamowieniaZPozycji(z.IdZamowienia))</option>
    }
</select>

pobintranetMVC/Views/Zamowienie/ZamowienieDoPozycji.cshtml
@using pobintranetMVC.Models
@{
    Layout = null;
    decimal max = 0;
    var producent = Request["producent"];

    if (!string.IsNullOrEmpty(Request["max"]))
    {
        try
        {
            max = Convert.ToDecimal(Request["max"]);
        }
        catch (Exception) { }
    }
    string pozycja = Request["pozycja"];
    string host = "/aplikacjeMVC";
    if(Request.Url.Host.Contains("localhost"))
    {
        host = "";
    }
}

@if (Help.CzyZamowieniaDlaKontrahenta(Convert.ToInt32(producent)))
{
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="~/Scripts/selectize.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css">
    <button type="button" class="przycisk_05" data-toggle="modal" data-target="#dodajModal" title="Dodaj do faktury numer zamówienia i kwotę">Dodaj zamówienie</button>
    <!-- Modal -->
    <div class="modal fade" id="dodajModal" tabindex="-1" role="dialog" aria-labelledby="Wgrywanie pliku" aria-hidden="true" style="padding-top:25vh;">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                @using (Html.BeginForm("DodajZakupDoZamowienia", "Zamowienie", FormMethod.Post,
                                     new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Dodawanie zamówienia do faktury kosztowej</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Zamknij">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" value="@pozycja" name="p" />
                        <input type="hidden" value="@Request["id"]" name="idz" />
                        <input type="hidden" value="@Request["zu"]" name="zu" />
                        <div class="form-group">
                            <label for="zamowienie">
                                Zamówienie:
                            </label>
                            <div id="select_zam">
                                <select id="selectzamowienie" name="id_zam" runat="server" class="wpisy_dp_male" style="text-align: left;" required>
                                    <option value="-1">Ładowanie zamówień...</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="kwota">
                                Kwota:
                            </label>
                            <input type="number" step="0.01" min="0" id="kwota" name="kwota" value="" class="form-control" required/>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
                        <input type="submit" value="Dodaj" class="btn btn-primary" />
                    </div>
                }
            </div>
        </div>
    </div>

    <script>
    $("#plikModal").on('shown.bs.modal', function (e) {
        $('.modal-backdrop').remove();
    });

    $('#select_zam').load("@host/Zamowienie/SelectZamowienia?producent=@producent", function () {
        $('#selectzamowienie').selectize({
            sortField: 'text',
            onInitialize: function () {
                this.trigger('change', this.getValue(), true);
            },
            onChange: function (value, isOnInitialize) {
                if ($('#selectzamowienie').find('option:selected').val()) {
                    $.get("@host/Zamowienie/SelectCena2?id=" + $('#selectzamowienie').find('option:selected').val() + " &max=" + @max, function (data) {
                        $("#kwota").val(data);
                    });
                }
            }
        });
    });
    </script>
}

pobintranetMVC/Views/Zamowienie/ZamowienieOpis.cshtml
@{
    Layout = null;
    List<zamowienieOpi> opisy = (List<zamowienieOpi>)ViewBag.Opisy;
    zamowieniaDokument zamowienie = (zamowieniaDokument)ViewBag.Zamowienie;
    var index = 0;
}

<script>
    function Zapisz() {
        var id_zam = $("#idzamowienia").val();
        var data_wprowadzenia = $("#data_wprowadzenia").val();
        var zu = $("#zu").val();
        var data = $("#data").val();
        var opis = $("#opis").val();

        window.location.href = encodeURI("/aplikacjeMVC/zamowienie/ZamowienieOpisDodaj?idzamowienia=" + id_zam + "&data_wprowadzenia=" + data_wprowadzenia + "&zu=" + zu + "&data=" + data + "&opis=" + opis);
    }
</script>

@*<form id="form" action="/aplikacjeMVC/Zamowienie/ZamowienieOpisDodaj" method="post">*@
<table border="1" style="min-width: 50%;">
    <tr id="buttonDodaj">
        <td colspan="5"><button type="button" onclick="$('#buttonDodaj').hide();$('#formDodaj').show();" class="przycisk_05">Dodaj</button></td>
    </tr>
    <tr id="formDodaj" style="display:none;">
        <td style="width: 10%">
            <label>@DateTime.Now.ToShortDateString()</label>
            <input type="hidden" name="idzamowienia" id="idzamowienia" value="@zamowienie.IdZamowienia" />
            <input type="hidden" name="data_wprowadzenia" id="data_wprowadzenia" value="@DateTime.Now.ToShortDateString()" />
            <input type="hidden" name="zu" id="zu" value="@Request["zu"]" />
        </td>
        <td style="width: 30%">
            <label for="opis">Data zdarzenia</label>
            <input type="date" name="data" id="data" value="@DateTime.Now.ToString("yyyy-MM-dd")" placeholder="Wpisz datę zdarzenia" class="wpisy_dp_male" />
        </td>
        <td colspan="2" style="width: 50%">
            <label for="opis">Opis zdarzenia</label>
            <input type="text" name="opis" id="opis" value="" placeholder="Wpisz opis zdarzenia" class="wpisy_dp_male" />
        </td>
        <td style="width: 10%">
            @*<input type="submit" value="Dodaj" />*@
            <button type="button" onclick="Zapisz();" class="przycisk_05">Zapisz</button>
            <button type="button" onclick="$('#buttonDodaj').show();$('#formDodaj').hide();" class="przycisk_05">Anuluj</button>
        </td>
    </tr>
    <tr>
        <td colspan="5">&nbsp;</td>
    </tr>
    <tr>
        <td style="width: 10%"><b>Lp</b></td>
        <td style="width: 30%"><b>Data</b></td>
        <td colspan="2" style="width: 50%"><b>Opis</b></td>
        <td style="width: 10%"><b>Akcje</b></td>
    </tr>
    @if (opisy.Count == 0)
    {
        <tr>
            <td colspan="5">BRAK</td>
        </tr>
    }
    @foreach (var opis in opisy)
    {
        index += 1;
        bool czyUser = opis.id_osoby == Convert.ToInt32(Request["zu"]) ? true : false;
        <tr>
            <td>@index</td>
            <td>@opis.data.ToString("dd-MM-yyyy")</td>
            <td colspan="2">@opis.opis</td>
            @if (czyUser)
            {
                <td>
                    <a href="/aplikacjeMVC/Zamowienie/UsunOpis?id=@opis.id&idzam=@opis.id_zamowienia">Usuń</a>
                </td>
            }
            else
            {
                <td>-</td>
            }
        </tr>
    }

</table>
@*</form>*@